### ISSUE TITLE
[QUESTION] - Architecture

### ISSUE THREAD

**Issue by go4cas** [forevertz/node-event-sourcing#2]
@BDav24, really keen to give this library a try! Love the simplicity vs other libs out there!

I have a couple of questions:
1. If I have a number of microservices, each managing data for different entities (e.g. Customer, Order, Invoice, Product), would you recommend to have a `Receiver`, `Archivist`, `Processor` & `State Reader` per microservice? Or, would it work to one of each for the entire system?
2. Do the examples on the `README` cover ALL the options for each of the components? Or, is there a seperate doc?

**Comment by BDav24** [comment]
Hi @go4cas, glad you like the simplicity :) (on this subject it's not event sourcing per se because the state is always read in the snapshot and never rebuilt from the event log).

1. Well it depends on what you want to do, but I'd try to go for simplicity first: except if some events are "overflowing the others" (for example track all clicks of millions of users), I'd keep the same "event receiver". For storage, see what's logical to keep together. Then if you go for (micro-)services you can have multiple processors and a state readers for each one.

2. There is no separate doc. You can check the examples : https://github.com/forevertz/node-event-sourcing/tree/master/examples

Hope it helps.
